language: java
jdk:
    - oraclejdk8
before_script:
    - wget http://services.gradle.org/distributions/gradle-4.1-bin.zip
    - unzip gradle-4.1-bin.zip
    - export GRADLE_HOME=$PWD/gradle-4.1
    - export PATH=$GRADLE_HOME/bin:$PATH
    - cd onlineBankingApplication
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)  